name: Build & Push to Google Container Registry

on:
  push:
    branches:
      - main    # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/picogk-service:latest .

    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/picogk-service:latest
